import os
import sys
import string
import shutil 

import numpy as np

import tensorflow as tf

@tf.keras.utils.register_keras_serializable()
def simple_standardization(input_data):
  lowercase = tf.strings.lower(input_data)
  return lowercase

dir_path = os.path.dirname(os.path.abspath(__file__))

model = tf.keras.models.load_model(os.path.join(dir_path, "classification_model"))

labels = ["chemistry/biological_chemistry",
          "chemistry/inorganic_chemistry", 
          "chemistry/organic_chemistry", 
          "chemistry/physical_chemistry"]

def predict_field(text):
  ilabel = np.argmax(model.predict([text])[0])
  return labels[ilabel]

print(predict_field("transition metal complex iron nickel cobalt inorganic"))
print(predict_field("physic schrodinger equation solve entropy boltzmann equilibria rate constants activation enthalpy"))
print(predict_field("genetics double helix dna rna atp"))
print(predict_field("alkane alkyne alkene carbonyl nucleophilic substitution mechanism"))
print(predict_field("epoxide synthesis isomers of alcohols"))
print(predict_field("Heterogeneously catalyzed oxidation alkenes edit epoxidation ethylene involves its reaction oxygen according following stoichiometry HC CH CH coz H direct reaction oxygen with alkenes useful only this epoxide Modi ed heterogeneous silver catalysts are typically employed Other alkenes fail react usefully even propylene though TS l supported Au catalysts can perform propylene epoxidation selectivelym Ole n alkene oxidation using organic peroxides metal catalysts edit Aside from ethylene oxide most epoxides are generated by treating alkenes with peroxide containing reagents which donate single oxygen atom Safety considerations weigh on these reactions because organic peroxides are prone spontaneous decomposition even combustion Metal complexes are useful catalysts epoxidations involving hydrogen peroxide alkyl hydroperoxides Peroxycarboxylic acids which are more electrophilic convert alkenes epoxides without intervention metal catalysts specialized applications other peroxide containing reagents are employed such as dimethyldioxirane Depending on mechanism reaction geometry alkene starting material cis trans epoxide diastereomers may be formed addition if there are other stereocenters present starting material they can uence stereochemistry epoxidation Metal catalyzed epoxidations were rst explored using tert butyl hydroperoxide TBHP Association TBHP with metal M generates active metal peroxy complex containing MOOR group which then transfers an center alkene"))
